### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by microbit-robert** [microbit-robert/makecode-microbit-ml-simulator#1]
- [ ] Is the repo name correct?
- [ ] Is the title in the HTML header correct?
- [ ] Is the name for the base set for GitHub Actions correct - see `vite.config.ts`?
- [ ] Add the same build script used for the previous version?
- [ ] Code review
- [ ] Readme review
- [ ] License review
